#!/usr/bin/env python3
"""Prepare SpriteCook MCP payloads from the local asset job manifest.

This script does not call SpriteCook directly. It creates reviewable JSON
payloads that match the SpriteCook tool schemas once OAuth/MCP is available.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PACK_ROOT = ROOT / "art" / "review-packs" / "spritecook-jobs-01"
ASSETS_PATH = PACK_ROOT / "spritecook-assets.json"
JOBS_PATH = PACK_ROOT / "spritecook-jobs-manifest.json"
PAYLOADS_ROOT = PACK_ROOT / "payloads"
STATUS_PATH = PACK_ROOT / "spritecook-batch-status.md"

DEFAULT_GENERATION_MODEL = "gemini-3.1-flash-image-preview"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def generation_payload(job: dict[str, Any], negative_prompt: str) -> dict[str, Any]:
    return {
        "tool": "generate_game_art",
        "arguments": {
            "prompt": job["prompt"],
            "width": job.get("width", 64),
            "height": job.get("height", 64),
            "variations": job.get("variations", 1),
            "pixel": job.get("pixel", True),
            "bg_mode": job.get("bg_mode", "transparent"),
            "smart_crop": job.get("smart_crop", True),
            "smart_crop_mode": job.get("smart_crop_mode", "tightest"),
            "model": job.get("model", DEFAULT_GENERATION_MODEL),
            "mode": "assets"
        },
        "negative_prompt": negative_prompt,
        "download_folder": job["download_folder"],
        "normalization_target": job["normalization_target"]
    }


def animation_payload(
    job: dict[str, Any],
    assets_by_label: dict[str, dict[str, Any]],
    negative_prompt: str
) -> dict[str, Any]:
    required_label = job["requires_asset_label"]
    asset = assets_by_label.get(required_label)
    asset_id = asset.get("asset_id") if asset else None
    blocked_by = None

    if not asset_id:
        blocked_by = {
            "asset_label": required_label,
            "reason": "missing SpriteCook asset_id",
            "asset_status": asset.get("status") if asset else "missing from spritecook-assets.json",
            "local_path": asset.get("local_path") if asset else None
        }

    return {
        "tool": "animate_game_art",
        "arguments": {
            "asset_id": asset_id or f"<fill asset_id for {required_label}>",
            "prompt": job["prompt"],
            "auto_enhance_prompt": False,
            "edge_margin": job.get("edge_margin", 6),
            "pixel": job.get("pixel", True),
            "output_frames": job["output_frames"],
            "output_format": job.get("output_format", "spritesheet"),
            "negative_prompt": negative_prompt,
            "removebg": job.get("removebg", "Basic"),
            "colors": 24
        },
        "blocked_by": blocked_by,
        "download_folder": job["download_folder"],
        "normalization_target": job["normalization_target"]
    }


def write_status(
    jobs: list[dict[str, Any]],
    payloads: list[dict[str, Any]]
) -> None:
    blocked = [payload for payload in payloads if payload.get("blocked_by")]
    runnable = [payload for payload in payloads if not payload.get("blocked_by")]
    lines = [
        "# SpriteCook Batch Status",
        "",
        "Generated by `scripts/prepare_spritecook_batch.py`.",
        "",
        "## Summary",
        "",
        f"- Total jobs: `{len(jobs)}`",
        f"- Runnable now: `{len(runnable)}`",
        f"- Blocked by missing `asset_id`: `{len(blocked)}`",
        "",
        "## First Required Manual Step",
        "",
        "Authenticate SpriteCook through the MCP/OAuth flow, import `art/review-packs/player/character_idle.png`, then put the returned `asset_id` into `spritecook-assets.json` for `player-final-idle-source-png`.",
        "",
        "Do not paste API keys into chat, prompts, shell commands, or repo files.",
        "",
        "## Payloads",
        ""
    ]

    for job in jobs:
        payload_path = PAYLOADS_ROOT / f"{job['id']}.json"
        lines.append(f"- `{job['id']}`: `{payload_path.relative_to(ROOT).as_posix()}`")

    STATUS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    assets = load_json(ASSETS_PATH)
    manifest = load_json(JOBS_PATH)
    assets_by_label = {asset["label"]: asset for asset in assets["assets"]}
    negative_prompt = manifest["global_negative_prompt"]
    payloads: list[dict[str, Any]] = []

    for job in manifest["jobs"]:
        download_folder = ROOT / job["download_folder"]
        download_folder.mkdir(parents=True, exist_ok=True)

        if job["tool"] == "generate_game_art":
            payload = generation_payload(job, negative_prompt)
        elif job["tool"] == "animate_game_art":
            payload = animation_payload(job, assets_by_label, negative_prompt)
        else:
            raise ValueError(f"Unsupported SpriteCook tool: {job['tool']}")

        payload = {
            "job_id": job["id"],
            "priority": job["priority"],
            **payload
        }
        payloads.append(payload)
        write_json(PAYLOADS_ROOT / f"{job['id']}.json", payload)

    write_status(manifest["jobs"], payloads)


if __name__ == "__main__":
    main()
